meta:
  environment: telegraf-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: telegraf
    networks:
      - name: telegraf-network

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: telegraf-pool
    cloud_properties:
      name: random

networks:
- name: telegraf-network
  type: manual
  subnets:
  - range: 10.244.10.8/29
    name: telegraf
    gateway: 10.244.10.9
    static:
      - 10.244.10.10
