meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: telegraf
    templates:
    - name: telegraf
      release: telegraf
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "please set just_install_package networks" ))

networks: (( param "please set networks" ))

properties:
properties:
  telegraf:
    outputs: |+
      [[outputs.riemann]]
        # URL of server
        url = "localhost:5555"
        # transport protocol to use either tcp or udp
        transport = "tcp"
    inputs: |+
      # Read metrics about cpu usage
      [[inputs.cpu]]
        # Whether to report per-cpu stats or not
        percpu = true
        # Whether to report total system cpu stats or not
        totalcpu = true
        # Comment this line if you want the raw CPU time metrics
        drop = ["time_*"]

      # Read metrics about disk usage by mount point
      [[inputs.disk]]
        # By default, telegraf gather stats for all mountpoints.
        # Setting mountpoints will restrict the stats to the specified mountpoints.
        # Mountpoints=["/"]

      # Read metrics about disk IO by device
      [[inputs.diskio]]
        # By default, telegraf will gather stats for all devices including
        # disk partitions.
        # Setting devices will restrict the stats to the specified devcies.
        # devices = ["sda","sdb"]
        # Uncomment the following line if you do not need disk serial numbers.
        # skip_serial_number = true
    hostname_prefix: warden
