meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  serial: false

jobs:
  - name: telegraf
    templates:
    - name: telegraf
      release: telegraf
    instances: 1
    persistent_disk: 0
    resource_pool: telegraf-pool
    networks: (( param "please set just_install_package networks" ))

networks: (( param "please set networks" ))

properties: {}
